### PR TITLE
ci: replace travis with github actions; add dependabot config

### PR DESCRIPTION
**Pull request by Fdawgs**

### CODE REVIEW

**Comment by mcollina** [comment]
This is still on travis, let's move to github action first

**Comment by Fdawgs** [comment]
> 
> 
> This is still on travis, let's move to github action first

👍 Amended this PR accordingly

**Comment by Fdawgs** [comment]
Example of this running on fork: https://github.com/Fdawgs/pino-caller/actions/runs/835575940

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
