### PR TITLE
Add source maps support

### LINKED ISSUE #14: caller shows lines in javascript but i use typescript
caller show lines in javascript but i use typescript
can you please add source-map support?

### PR DESCRIPTION
**Pull request by phra**
fixes #14 

image

### CODE REVIEW

**Comment by Dids** [comment]
Any updates on this?

**Comment by gregory** [comment]
@phra @davidmarkclements  any update?

**Comment by phra** [comment]
@mcollina what about this one too?

**Comment by phra** [comment]
i ended up in a strange situation: `npm test` passes, but `npm run coverage` doesn't. executing them manually works too. not really sure about what the issue is. 

1. `npm test`
image

2. `npm run coverage`
image

3. `env NODE_ENV=development node tests/test-ts.js`
image

**Comment by phra** [comment]
merging it as is will break the tests as explained in https://github.com/pinojs/pino-caller/pull/15#issuecomment-557801912

**Comment by gregory** [comment]
ping @phra

**Pull request merged**
